<div class="alert alert-block alert-info">
    <h1>Natural Language Processing</h1>
    <h3>General Information:</h3>
    <p>Please do not add or delete any cells. Answers belong into the corresponding cells (below the question). If a function is given (either as a signature or a full function), you should not change the name, arguments or return value of the function.<br><br> If you encounter empty cells underneath the answer that can not be edited, please ignore them, they are for testing purposes.<br><br>When editing an assignment there can be the case that there are variables in the kernel. To make sure your assignment works, please restart the kernel and run all cells before submitting (e.g. via <i>Kernel -> Restart & Run All</i>).</p>
    <p>Code cells where you are supposed to give your answer often include the line  ```raise NotImplementedError```. This makes it easier to automatically grade answers. If you edit the cell please outcomment or delete this line.</p>
    <h3>Submission:</h3>
    <p>Please submit your notebook via the web interface (in the main view -> Assignments -> Submit). The assignments are due on <b>Wednesday at 15:00</b>. If this does not work there is a submission slot on LEA.</p>
    <h3>Group Work:</h3>
    <p>You are allowed to work in groups of up to two people. Please enter the UID (your username here) of each member of the group into the next cell. We apply plagiarism checking, so do not submit solutions from other people except your team members. If an assignment has a copied solution, the task will be graded with 0 points for all people with the same solution.</p>
    <h3>Questions about the Assignment:</h3>
    <p>If you have questions about the assignment please post them in the LEA forum before the deadline. Don't wait until the last day to post questions.</p>
    
</div>

In [ ]:
'''
Group Work:
Enter the UID of each team member into the variables. 
If you work alone please leave the second variable empty.
'''
member1 = ''
member2 = ''

# Edit Distance

We want to calculate the edit distance between a list of pairs of words.

The allowed operations are:

- Deletion (delete one character)
- Insertion (add one character)
- Substituion (exchange one character for another)

## 1.1) Deletion [5 Points]

Write a function ```delete(word, char_index)``` that deletes the character at index ```char_index``` from the word ```word``` and returns the resulting string.

In [2]:
def delete(word: str, char_index: int) -> str:
    new_word = word[0:char_index] + word[char_index+1:]
    return new_word
    
print(delete('language', 3)) # Should print lanuage

lanuage


In [3]:
# This is a test cell, please ignore it!

## 1.2) Insertion [5 Points]

Write a function ```insert(word, char_index, char)``` which inserts the character ```char``` into the word ```word``` at index ```char_index```.

In [4]:
def insert(word: str, char_index: int, char: str) -> str:
    new_word = word[:char_index] + char + word[char_index:]
    return new_word
    
print(insert('language', 3, 'b')) # Should print lanbguage

lanbguage


In [5]:
# This is a test cell, please ignore it!

## 1.3) Substitution [5 Points]

Write a function ```substitute(word, char_index, char)``` which replaces the character at index ```char_index``` of the word ```word``` with the character ```char```.

In [6]:
def substitute(word: str, char_index: int, char: str) -> str:
    new_word = list(word)
    new_word[char_index] = char
    return ''.join(new_word)
    
print(substitute('language', 3, 'b')) # Should print lanbuage

lanbuage


In [7]:
# This is a test cell, please ignore it!

## 2) Branching Factor [5 Points]

Given the word ```language``` and assuming we only work with the lower case letters of the English alphabet (a-z), how many branches do we have from the word ```language```, using only substituion, deletion and insertion?

Give the number of:
- deletions
- insertions
- substitutions

Save them in corresponding variables (```n_delete```, ```n_insert``` and ```n_substitute```).

*Hint: You can calculate this by hand, too*

In [8]:
n_delete = 0
n_insert = 0
n_substitute = 0

my_word = 'language'
english_alphabet = 'abcdefghijklmnopqrstuvwxyz' 

n_delete = len(my_word)
n_insert = (len(my_word) + 1) * ( len(english_alphabet))
n_substitute = len(my_word) * ( len(english_alphabet) - 1)

print('There are {} deletions, {} insertions and {} substitutions.'.format(n_delete, n_insert, n_substitute))

There are 8 deletions, 234 insertions and 200 substitutions.


In [9]:
# This is a test cell, please ignore it!

## 3.1) Levenshtein Edit Distance [25 Points]

Implement the algorithm given in the slideset 1A - Edit Distance on slide 14.

The function ```levenshtein(word, other_word)``` takes in two words and calculates the distance as an integer. Please complete the function and test with the example on the slides.

Comment your code to explain what each step is doing. We expect you to be able to explain your solution in class so don't copy solutions from the Internet.

*Hint: To create a matrix in Python you can use the numpy package. The command ```np.zeros((r, c), dtype=int)``` creates a matrix with ```r``` rows and ```c``` columns of type ```int``` which is filled with zeros.*

In [62]:
import numpy as np

def levenshtein(word: str, other_word: str) -> int:
    #lists to compare chars of the words
    w_list = list(word)
    o_list = list(other_word)
    #length of the words
    w_len = len(word)
    o_len = len(other_word)
    
    #D matrix of size (N+1, M+1)
    D = np.zeros((w_len+1, o_len+1), dtype=int)
    #initialize D(i, 0) = i
    D[:,0] = np.arange(w_len+1)
    #initialize D(0, j) = j
    D[0] = np.arange(o_len+1)
    for i in range(1, w_len + 1):
        for j in range(1, o_len + 1):
            #Min Edit Distance (Levenshtein) formula
            if(w_list[i - 1] != o_list[j - 1]):
                #if the letters at the current position are not equal
                D[i, j] = min(D[i-1, j] + 1, D[i, j-1] + 1, D[i-1, j-1] + 2)
            else:
                D[i, j] = min(D[i-1, j] + 1, D[i, j-1] + 1, D[i-1, j-1])
    #return D(N,M)
    return D[w_len, o_len]
    
print(levenshtein('intention', 'execution')) # Expected output is 8 = 

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0 0]
 [6 0 0 0 0 0 0 0 0 0]
 [7 0 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0 0]]
[[0 1 2 3 4 5 6 7 8 9]
 [1 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0 0]
 [6 0 0 0 0 0 0 0 0 0]
 [7 0 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0 0]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  3  4  5  6  7  8]
 [ 2  3  4  5  4  5  6  7  8  9]
 [ 3  4  5  6  5  6  7  8  9 10]
 [ 4  5  6  7  6  7  8  9 10 11]
 [ 5  6  7  8  7  8  9 10 11 12]
 [ 6  7  8  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  7  8  9 10 11 10  9  8]]
8


In [11]:
# This is a test cell, please ignore it!

## 3.2) Finding Words with Minimum and Maximum Edit Distance [10 Points]

You are given a list of words from the book ```Emma``` by Jane Austen (see next cell).

Find the words with the minimum edit distance to the following words:

- consequently
- intelligence
- delights

Save your answer in as a list of tuples.
Each tuple should contain the word (e.g. intelligence), the word with the minimum edit distance and the distance. Use your levensthein function for this.

Example: ```solution = [('telling', 'felling', 2), ...]```

*Hint: If the next cell throws an error regarding missing files, execute the following in a new cell and try again:*

```
import nltk
nltk.download('gutenberg')
```

In [15]:
from nltk.corpus import gutenberg

words = set(gutenberg.words('austen-emma.txt'))

solution = []

my_set = set(['consequently', 'intelligence', 'delights'])

for my_word in my_set:
    min_distance = np.inf
    min_word = ''
    
    for other_word in words:
        #check if the word is not the same
        if my_word == other_word:
            continue
        #obtain minimum edit distance
        current_distance = levenshtein(my_word, other_word)
        if(current_distance < min_distance):
            min_distance = current_distance
            min_word = other_word
            
    solution.append((my_word, min_word, min_distance))


print(solution)

[('intelligence', 'intelligent', 3), ('delights', 'delight', 1), ('consequently', 'consequent', 2)]


In [ ]:
# This is a test cell, please ignore it!

## 4.1) Statistical Spell Checker [35 Points]

We now want to build a statistical spell checker. The main idea is to have a dictionary of words and how often they appear in a certain training set and use this for looking up the probability of a word.

Now we take in a potentially mispelled word and do the following:

1. If the word is in our dictionary, return the word
2. Else create all possible edits of the word by deleting, inserting and substituting.
3. For these edits, check if they are in our dictionary and return the one with the max count
4. If none of the edits are in the dictionary, return the original word

In [68]:
from typing import Dict
from collections import Counter

class Spellchecker:
    
    def __init__(self, counts: Dict[str, int]):
        
        self.dictionary = counts
        
    def correct(self, word: str) -> str:
        '''
        Take a word and return the corrected word
        
        Arguments:
            word       -- word to correct
        Returns:
            correction -- corrected word or word itself if no correction was found
        '''
        words = []
        #deletion
        for i in range(len(word)):
                deleted = self.delete(word,i)
                words.append(deleted)  
        # Insertion
        for k in range(len(word)+1):
                english_alphabet = 'abcdefghijklmnopqrstuvwxyz' 
                for character in english_alphabet:
                    inserted = self.insert(word,k,character)
                    words.append(inserted)
        # Substitution           
        for u in range(len(word)):
            english_alphabet = 'abcdefghijklmnopqrstuvwxyz' 
            for character in english_alphabet:
                if character != word[u]:
                    substituted = self.substitute(word,u,character)
                    words.append(substituted)

        if word in self.dictionary:
            return word
        else:
        # extract maximum frequency word from the dictionary
            dic = {}
            for words in words:
                if words in self.dictionary:
                    value = self.dictionary[words]
                    dic[words] = value
            # Check if dictionary if empty
            if bool(dic):
                Keymax = max(dic, key=dic.get) 
                return Keymax
            else:
                return word
            
            
    def delete(self, word: str, char_index: int) -> str:
        new_word = word[0:char_index] + word[char_index+1:]
        return new_word
      
    def insert(self, word: str, char_index: int, char: str) -> str:
        new_word = word[:char_index] + char + word[char_index:]
        return new_word
    
    def substitute(self, word: str, char_index: int, char: str) -> str:
        new_word = list(word)
        new_word[char_index] = char
        return ''.join(new_word)

    
# Load in the words from Jane Austens Emma and count their occurence (lowercase)
counts = Counter([w.lower() for w in gutenberg.words('austen-emma.txt')])

# print(counts)
# Create the spellchecker
speller = Spellchecker(counts)

# Correct the word kanguage
print(speller.correct('kanguage'))

language


In [ ]:
# This is a test cell, please ignore it!

## 4.2) Application of Spellchecker [10 Points]

Please use your spellchecker together with regular expressions to correct the sentences given in the list ```sentences``` and save the corrected version (as a single string, not as a list of words) in the list ```corrected```.

In [57]:
import re

sentences = [
    'shi waas sleiping',
    'hi ws saing frendly zhings',
    'zhe doug clan walg frast',
    'emmo bpy kane usten'
]

corrected = []
# Iterate through list
for string in sentences:
    # break into individual string
    new = string.split(' ')
    temp = []
    # Do the correction
    for words in new:
        speller = Spellchecker(counts)
        corrected_word = speller.correct(words)
        temp.append(corrected_word)
    # Merge together
    update_string = ' '.join(temp)   
    corrected.append(update_string)
    
for correction in corrected:
    print(correction)

she was sleeping
i was saying friendly things
the dog can walk fast
emma by jane austen


In [ ]:
# This is a test cell, please ignore it!